schema: 'https://interviewdream-backend.herokuapp.com/graphql'
documents: src/graphql/documents/**/*.graphql
extensions:
  codegen:
    generates:
      src/graphql/generated/graphql.schema.json:
        plugins:
          - introspection
      src/graphql/generated/graphql.types.ts:
        plugins:
          - typescript
      src/graphql/generated:
        preset: near-operation-file
        presetConfig:
          extension: .graphql-gen.ts
          baseTypesPath: graphql.types.ts
        plugins:
          - typescript-operations
          - typescript-apollo-angular
    hooks:
      afterAllFileWrite:
        - prettier --write
    overwrite: true
