import { SideNavModel } from './side-nav.model';

export const SIDE_NAV_CONTENT: SideNavModel[] = [
  {
    icon: 'home',
    label: 'shared.sideNav.home',
    name: 'home',
    route: 'dashboard/home',
    order: 100,
    disabled: true,
  },
  {
    icon: 'message',
    label: 'shared.sideNav.chat',
    name: 'chat',
    route: 'dashboard/chat',
    order: 200,
    disabled: false,
  },
  {
    icon: 'notifications',
    label: 'shared.sideNav.notifications',
    name: 'notifications',
    route: 'dashboard/notfifications',
    order: 300,
    disabled: true,
  },
  {
    icon: 'person',
    label: 'shared.sideNav.profile',
    name: 'profile',
    order: 400,
    disabled: false,
    subList: [
      {
        label: 'shared.sideNav.publicProfile',
        name: 'publicProfile',
        route: 'dashboard/profile',
        order: 100,
        disabled: false,
      },
      {
        label: 'shared.sideNav.editProfile',
        name: 'editProfile',
        route: 'dashboard/profile?edit=true',
        queryParams: { edit: true },
        order: 200,
        disabled: false,
      },
    ],
  },
  {
    icon: 'description',
    label: 'shared.sideNav.courses',
    name: 'courses',
    order: 500,
    disabled: false,
    subList: [
      {
        label: 'shared.sideNav.allCourses',
        name: 'allCourses',
        route: 'dashboard/courses',
        order: 100,
        disabled: false,
      },
      {
        label: 'shared.sideNav.myCourses',
        name: 'myCourses',
        route: 'dashboard/my-courses',
        order: 200,
        disabled: true,
      },
    ],
  },
  {
    icon: 'description',
    label: 'shared.sideNav.QAAndPapers',
    name: 'QAAndPapers',
    order: 700,
    disabled: false,
    subList: [
      {
        label: 'shared.sideNav.allPapers',
        name: 'allPapers',
        route: 'dashboard/papers',
        order: 100,
        disabled: false,
      },
      {
        label: 'shared.sideNav.createPracticePaper',
        name: 'createPracticePaper',
        route: 'dashboard/papers/id',
        order: 200,
        disabled: true,
      },
      {
        label: 'shared.sideNav.editPracticePaper',
        name: 'editPracticePaper',
        route: 'dashboard/papers/edit',
        order: 300,
        disabled: true,
      },
      {
        label: 'shared.sideNav.allQuestions',
        name: 'allQuestions',
        route: 'dashboard/questions/all',
        order: 400,
        disabled: true,
      },
    ],
  },
  {
    icon: 'web_asset',
    label: 'shared.sideNav.onlineTests',
    name: 'onlineTests',
    order: 800,
    disabled: false,
    subList: [
      {
        label: 'shared.sideNav.allTests',
        name: 'allTests',
        route: 'dashboard/tests',
        order: 100,
        disabled: true,
      },
      {
        label: 'shared.sideNav.createTest',
        name: 'createTest',
        route: 'dashboard/test/create',
        order: 200,
        disabled: true,
      },
      {
        label: 'shared.sideNav.editTest',
        name: 'editTest',
        route: 'dashboard/test/edit',
        order: 300,
        disabled: true,
      },
    ],
  },
  {
    icon: 'payment',
    label: 'shared.sideNav.payment',
    name: 'payment',
    route: 'payment',
    order: 900,
    disabled: true,
  },
  {
    icon: 'settings',
    label: 'shared.sideNav.account',
    name: 'account',
    route: 'account',
    order: 1000,
    disabled: true,
  },
  {
    icon: 'group',
    label: 'shared.sideNav.administration',
    name: 'administration',
    route: 'admin',
    order: 1100,
    disabled: true,
  },
  {
    icon: 'help',
    label: 'shared.sideNav.help',
    name: 'help',
    route: 'dashboard/help',
    order: 1200,
    disabled: false,
  },
  {
    icon: 'logout',
    label: 'shared.sideNav.logout',
    name: 'logout',
    method: true,
    order: 1300,
    disabled: false,
  },
];
