import { SideNavModel } from './side-nav.model';

export const SIDE_NAV_CONTENT: SideNavModel[] = [
  {
    icon: 'home',
    label: 'Home',
    name: 'home',
    route: 'dashboard/home',
    order: 100,
    disabled: true,
  },
  {
    icon: 'message',
    label: 'Chat',
    name: 'chat',
    route: 'dashboard/chat',
    order: 200,
    disabled: false,
  },
  {
    icon: 'notifications',
    label: 'Notifications',
    name: 'notifications',
    route: 'dashboard/notfifications',
    order: 300,
    disabled: true,
  },
  {
    icon: 'person',
    label: 'Profile',
    name: 'profile',
    order: 400,
    disabled: false,
    subList: [
      {
        label: 'Public profile',
        name: 'publicProfile',
        route: 'dashboard/profile',
        order: 100,
        disabled: false,
      },
      {
        label: 'Edit profile',
        name: 'editProfile',
        route: 'dashboard/profile?edit=true',
        queryParams: { edit: true },
        order: 200,
        disabled: false,
      },
    ],
  },
  {
    icon: 'description',
    label: 'Courses',
    name: 'courses',
    order: 500,
    disabled: false,
    subList: [
      {
        label: 'All courses',
        name: 'allCourses',
        route: 'dashboard/courses',
        order: 100,
        disabled: false,
      },
      {
        label: 'My courses',
        name: 'myCourses',
        route: 'dashboard/my-courses',
        order: 200,
        disabled: true,
      },
    ],
  },
  {
    icon: 'description',
    label: 'QA & Papers',
    name: 'QAAndPapers',
    order: 700,
    disabled: false,
    subList: [
      {
        label: 'All papers',
        name: 'allPapers',
        route: 'dashboard/papers',
        order: 100,
        disabled: false,
      },
      {
        label: 'Create practice paper',
        name: 'createPracticePaper',
        route: 'dashboard/papers/id',
        order: 200,
        disabled: true,
      },
      {
        label: 'Edit practice paper',
        name: 'editPracticePaper',
        route: 'dashboard/papers/edit',
        order: 300,
        disabled: true,
      },
      {
        label: 'All questions',
        name: 'allQuestions',
        route: 'dashboard/questions/all',
        order: 400,
        disabled: true,
      },
    ],
  },
  {
    icon: 'web_asset',
    label: 'Online Tests',
    name: 'onlineTests',
    order: 800,
    disabled: false,
    subList: [
      {
        label: 'All tests',
        name: 'allTests',
        route: 'dashboard/tests',
        order: 100,
        disabled: true,
      },
      {
        label: 'Create test',
        name: 'createTest',
        route: 'dashboard/test/create',
        order: 200,
        disabled: true,
      },
      {
        label: 'Edit test',
        name: 'editTest',
        route: 'dashboard/test/edit',
        order: 300,
        disabled: true,
      },
    ],
  },
  {
    icon: 'payment',
    label: 'Payment',
    name: 'payment',
    route: 'payment',
    order: 900,
    disabled: true,
  },
  {
    icon: 'settings',
    label: 'Account',
    name: 'account',
    route: 'account',
    order: 1000,
    disabled: true,
  },
  {
    icon: 'group',
    label: 'Administration',
    name: 'administration',
    route: 'admin',
    order: 1100,
    disabled: true,
  },
  {
    icon: 'help',
    label: 'Help',
    name: 'help',
    route: 'help',
    order: 1200,
    disabled: true,
  },
  {
    icon: 'logout',
    label: 'Logout',
    name: 'logout',
    method: true,
    order: 1300,
    disabled: false,
  },
];
